### ユーザー一覧取得(Level)
GET  http://localhost:8000/api/users/index?name=user01
Accept:  application/json

### ユーザー情報取得
GET http://localhost:8000/api/users/7
Accept: application/json

### ユーザー登録
POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "zzz",
    "level": "0",
    "experience": "0"
}

### ユーザー更新
POST  http://localhost:8000/api/users/update
Content-Type: application/json
Accept:  application/json

{
    "user_id": 5,
    "name": "jobi",
    "level": 2,
    "experience": 1
}

### ユーザー更新
POST  http://localhost:8000/api/users/update
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 4|kkeRirTn8wI3WGVwcgOiySWglfU7fSJQ4Vm4Ljktb0a0a65e

{
    "name": "zzz",
    "level": 111,
    "experience": 222
}

### ユーザー詳細情報更新
POST  http://localhost:8000/api/user_detail/update
Content-Type: application/json
Accept:  application/json

{
    "user_id": 5,
    "name": "jobi",
    "level": 2,
    "experience": 1
}
